apiVersion: v1
kind: Service
metadata:
  name: kandev
  labels:
    app: kandev
spec:
  type: ClusterIP
  selector:
    app: kandev
  ports:
    - name: http
      port: 38429
      targetPort: backend
      protocol: TCP
