package launcher

import (
	"errors"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

func TestParseServiceArgsAcceptsSystemRunAs(t *testing.T) {
	args, err := parseServiceArgs([]string{"install", "--system", "--run-as", "alice"})
	if err != nil {
		t.Fatalf("parseServiceArgs() error = %v, want --run-as to be accepted for system install", err)
	}
	if args.Action != actionInstall || !args.System {
		t.Fatalf("parsed args = %#v, want system install", args)
	}
	if args.RunAs != "alice" {
		t.Fatalf("RunAs = %q, want alice", args.RunAs)
	}
	if _, err := parseServiceArgs([]string{"install", "--run-as", "alice"}); err == nil {
		t.Fatal("parseServiceArgs() accepted --run-as for a user service")
	}
	if _, err := parseServiceArgs([]string{"restart", "--system", "--run-as", "alice"}); err == nil {
		t.Fatal("parseServiceArgs() accepted --run-as for a non-install action")
	}
}

func TestResolveSystemServiceUserRequiresExplicitRootOnFirstInstall(t *testing.T) {
	t.Setenv("SUDO_USER", "root")
	_, err := resolveSystemServiceUser(
		serviceArgs{Action: actionInstall, System: true},
		filepath.Join(t.TempDir(), "missing.service"),
		nativeServiceManagerSystemd,
	)
	if err == nil || !strings.Contains(err.Error(), "--run-as") {
		t.Fatalf("resolveSystemServiceUser() error = %v, want explicit --run-as guidance", err)
	}
}

func TestParseManagedServiceUsers(t *testing.T) {
	systemUser, found, err := parseManagedSystemdUser([]byte("[Service]\nExecStart=/bin/kandev\n"), "kandev.service")
	if err != nil || !found || systemUser != "root" {
		t.Fatalf("parseManagedSystemdUser() = %q, %v, %v; want root, true, nil", systemUser, found, err)
	}
	launchdUser, found, err := parseManagedLaunchdUser([]byte(`<?xml version="1.0"?><plist><dict><key>UserName</key><string>alice</string></dict></plist>`), "kandev.plist")
	if err != nil || !found || launchdUser != "alice" {
		t.Fatalf("parseManagedLaunchdUser() = %q, %v, %v; want alice, true, nil", launchdUser, found, err)
	}
	if _, _, err := parseManagedLaunchdUser([]byte(`<?xml version="1.0"?><plist><dict><key>UserName</key><integer>501</integer></dict></plist>`), "kandev.plist"); err == nil {
		t.Fatal("parseManagedLaunchdUser() accepted a non-string UserName")
	}
}

func TestInstallSystemdPreservesExistingManagedUser(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("system service identity is unsupported on Windows")
	}
	originalExecutablePath := executablePath
	originalExecuteServiceCommand := executeServiceCommand
	originalServicePrintln := servicePrintln
	originalLookup := lookupNativeServiceOwner
	t.Cleanup(func() {
		executablePath = originalExecutablePath
		executeServiceCommand = originalExecuteServiceCommand
		servicePrintln = originalServicePrintln
		lookupNativeServiceOwner = originalLookup
	})

	current, err := user.Current()
	if err != nil {
		t.Fatal(err)
	}
	currentUID, currentGID, err := lookupNativeServiceOwner(current.Username)
	if err != nil {
		t.Fatal(err)
	}

	tmp := t.TempDir()
	homeDir := filepath.Join(tmp, "home")
	if err := os.Mkdir(homeDir, 0o700); err != nil {
		t.Fatal(err)
	}
	unitPath := filepath.Join(tmp, "kandev.service")
	original := "# managed by kandev — regenerated by `kandev service install`\n[Service]\nUser=alice\n"
	if err := os.WriteFile(unitPath, []byte(original), 0o640); err != nil {
		t.Fatal(err)
	}

	lookupNativeServiceOwner = func(string) (int, int, error) { return currentUID, currentGID, nil }
	executablePath = func() (string, error) { return "/opt/kandev/bin/kandev", nil }
	executeServiceCommand = func(string, ...string) error { return nil }
	servicePrintln = func(string) {}
	t.Setenv("SUDO_USER", "root")

	if code := installSystemd(
		serviceArgs{Action: actionInstall, System: true, HomeDir: homeDir, NoBootStart: true},
		BuildInfo{Version: "test"}, unitPath,
	); code != 0 {
		t.Fatalf("installSystemd() = %d, want 0", code)
	}

	unit, err := os.ReadFile(unitPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(unit), "User=alice\n") {
		t.Fatalf("reinstalled unit lost preserved service user:\n%s", unit)
	}
	if !strings.Contains(string(unit), "Environment=KANDEV_SERVICE_MODE=system") {
		t.Fatalf("reinstalled unit is not a system service:\n%s", unit)
	}
}

func TestInstallSystemdRejectsManagedHomeOwnerMismatchBeforeWrite(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("system service identity is unsupported on Windows")
	}
	originalExecutablePath := executablePath
	originalExecuteServiceCommand := executeServiceCommand
	originalServicePrintln := servicePrintln
	originalLookup := lookupNativeServiceOwner
	t.Cleanup(func() {
		executablePath = originalExecutablePath
		executeServiceCommand = originalExecuteServiceCommand
		servicePrintln = originalServicePrintln
		lookupNativeServiceOwner = originalLookup
	})

	tmp := t.TempDir()
	homeDir := filepath.Join(tmp, "home")
	if err := os.Mkdir(homeDir, 0o700); err != nil {
		t.Fatal(err)
	}
	unitPath := filepath.Join(tmp, "kandev.service")
	original := "# managed by kandev — regenerated by `kandev service install`\n[Service]\nUser=alice\n"
	if err := os.WriteFile(unitPath, []byte(original), 0o640); err != nil {
		t.Fatal(err)
	}

	lookupNativeServiceOwner = func(string) (int, int, error) { return 1234, 5678, nil }
	executablePath = func() (string, error) { return "/opt/kandev/bin/kandev", nil }
	servicePrintln = func(string) {}
	var managerCalls int
	executeServiceCommand = func(string, ...string) error {
		managerCalls++
		return nil
	}

	code := installSystemd(
		serviceArgs{Action: actionInstall, System: true, HomeDir: homeDir, NoBootStart: true},
		BuildInfo{Version: "test"}, unitPath,
	)
	if code == 0 {
		t.Fatal("installSystemd() = 0, want owner mismatch failure")
	}
	if managerCalls != 0 {
		t.Fatalf("service manager commands = %d, want none after preflight failure", managerCalls)
	}
	definition, err := os.ReadFile(unitPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(definition) != original {
		t.Fatalf("service definition changed after owner mismatch:\n%s", definition)
	}
}

func TestInstallLaunchdPreservesExistingManagedUser(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("system service identity is unsupported on Windows")
	}
	originalExecutablePath := executablePath
	originalExecuteServiceCommand := executeServiceCommand
	originalLaunchctlCommand := launchctlCommand
	originalLaunchctlSleep := launchctlSleep
	originalServicePrintln := servicePrintln
	originalLookup := lookupNativeServiceOwner
	t.Cleanup(func() {
		executablePath = originalExecutablePath
		executeServiceCommand = originalExecuteServiceCommand
		launchctlCommand = originalLaunchctlCommand
		launchctlSleep = originalLaunchctlSleep
		servicePrintln = originalServicePrintln
		lookupNativeServiceOwner = originalLookup
	})

	current, err := user.Current()
	if err != nil {
		t.Fatal(err)
	}
	currentUID, currentGID, err := lookupNativeServiceOwner(current.Username)
	if err != nil {
		t.Fatal(err)
	}

	tmp := t.TempDir()
	homeDir := filepath.Join(tmp, "home")
	if err := os.Mkdir(homeDir, 0o700); err != nil {
		t.Fatal(err)
	}
	plistPath := filepath.Join(tmp, "com.kdlbs.kandev.plist")
	original := "<!-- managed by kandev -->\n<plist><dict><key>UserName</key><string>alice</string></dict></plist>\n"
	if err := os.WriteFile(plistPath, []byte(original), 0o640); err != nil {
		t.Fatal(err)
	}

	lookupNativeServiceOwner = func(string) (int, int, error) { return currentUID, currentGID, nil }
	executablePath = func() (string, error) { return "/opt/kandev/bin/kandev", nil }
	executeServiceCommand = func(string, ...string) error { return nil }
	launchctlCommand = func(args ...string) error {
		if len(args) > 0 && args[0] == "print" {
			return errors.New("not loaded")
		}
		return nil
	}
	launchctlSleep = func(time.Duration) {}
	servicePrintln = func(string) {}

	if code := installLaunchd(
		serviceArgs{Action: actionInstall, System: true, HomeDir: homeDir, NoBootStart: true},
		BuildInfo{Version: "test"}, plistPath, "system/com.kdlbs.kandev", "system",
	); code != 0 {
		t.Fatalf("installLaunchd() = %d, want 0", code)
	}

	plist, err := os.ReadFile(plistPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(plist), "<key>UserName</key>\n  <string>alice</string>") {
		t.Fatalf("reinstalled plist lost preserved service user:\n%s", plist)
	}
}

func TestInstallLaunchdRejectsManagedHomeOwnerMismatchBeforeWrite(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("system service identity is unsupported on Windows")
	}
	originalExecutablePath := executablePath
	originalExecuteServiceCommand := executeServiceCommand
	originalLaunchctlCommand := launchctlCommand
	originalLaunchctlSleep := launchctlSleep
	originalServicePrintln := servicePrintln
	originalLookup := lookupNativeServiceOwner
	t.Cleanup(func() {
		executablePath = originalExecutablePath
		executeServiceCommand = originalExecuteServiceCommand
		launchctlCommand = originalLaunchctlCommand
		launchctlSleep = originalLaunchctlSleep
		servicePrintln = originalServicePrintln
		lookupNativeServiceOwner = originalLookup
	})

	current, err := user.Current()
	if err != nil {
		t.Fatal(err)
	}
	currentUID, _, err := lookupNativeServiceOwner(current.Username)
	if err != nil {
		t.Fatal(err)
	}
	mismatchUID := currentUID + 1
	if mismatchUID == currentUID {
		mismatchUID++
	}

	tmp := t.TempDir()
	homeDir := filepath.Join(tmp, "home")
	if err := os.Mkdir(homeDir, 0o700); err != nil {
		t.Fatal(err)
	}
	plistPath := filepath.Join(tmp, "com.kdlbs.kandev.plist")
	original := "<!-- managed by kandev -->\n<plist><dict><key>UserName</key><string>alice</string></dict></plist>\n"
	if err := os.WriteFile(plistPath, []byte(original), 0o640); err != nil {
		t.Fatal(err)
	}

	lookupNativeServiceOwner = func(string) (int, int, error) { return mismatchUID, 5678, nil }
	executablePath = func() (string, error) { return "/opt/kandev/bin/kandev", nil }
	servicePrintln = func(string) {}
	var managerCalls, launchctlCalls int
	executeServiceCommand = func(string, ...string) error {
		managerCalls++
		return nil
	}
	launchctlCommand = func(...string) error {
		launchctlCalls++
		return nil
	}
	launchctlSleep = func(time.Duration) {}

	code := installLaunchd(
		serviceArgs{Action: actionInstall, System: true, HomeDir: homeDir, NoBootStart: true},
		BuildInfo{Version: "test"}, plistPath, "system/com.kdlbs.kandev", "system",
	)
	if code == 0 {
		t.Fatal("installLaunchd() = 0, want owner mismatch failure")
	}
	if managerCalls != 0 || launchctlCalls != 0 {
		t.Fatalf("service commands = manager:%d launchctl:%d, want none after preflight failure", managerCalls, launchctlCalls)
	}
	definition, err := os.ReadFile(plistPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(definition) != original {
		t.Fatalf("service definition changed after owner mismatch:\n%s", definition)
	}
}
